// Generated by jextract

package jpassport.test.extracted;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ComplexPassing {
 *     int s_ID;
 *     struct PassingData s_passingData;
 *     struct PassingData *s_ptrPassingData;
 *     char *s_string;
 * }
 * }
 */
public class ComplexPassing {

    ComplexPassing() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        library_h.C_INT.withName("s_ID"),
        MemoryLayout.paddingLayout(4),
        PassingData.layout().withName("s_passingData"),
        library_h.C_POINTER.withName("s_ptrPassingData"),
        library_h.C_POINTER.withName("s_string")
    ).withName("ComplexPassing");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt s_ID$LAYOUT = (OfInt)$LAYOUT.select(groupElement("s_ID"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int s_ID
     * }
     */
    public static final OfInt s_ID$layout() {
        return s_ID$LAYOUT;
    }

    private static final long s_ID$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int s_ID
     * }
     */
    public static final long s_ID$offset() {
        return s_ID$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int s_ID
     * }
     */
    public static int s_ID(MemorySegment struct) {
        return struct.get(s_ID$LAYOUT, s_ID$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int s_ID
     * }
     */
    public static void s_ID(MemorySegment struct, int fieldValue) {
        struct.set(s_ID$LAYOUT, s_ID$OFFSET, fieldValue);
    }

    private static final GroupLayout s_passingData$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("s_passingData"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct PassingData s_passingData
     * }
     */
    public static final GroupLayout s_passingData$layout() {
        return s_passingData$LAYOUT;
    }

    private static final long s_passingData$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct PassingData s_passingData
     * }
     */
    public static final long s_passingData$offset() {
        return s_passingData$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct PassingData s_passingData
     * }
     */
    public static MemorySegment s_passingData(MemorySegment struct) {
        return struct.asSlice(s_passingData$OFFSET, s_passingData$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct PassingData s_passingData
     * }
     */
    public static void s_passingData(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, s_passingData$OFFSET, s_passingData$LAYOUT.byteSize());
    }

    private static final AddressLayout s_ptrPassingData$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("s_ptrPassingData"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct PassingData *s_ptrPassingData
     * }
     */
    public static final AddressLayout s_ptrPassingData$layout() {
        return s_ptrPassingData$LAYOUT;
    }

    private static final long s_ptrPassingData$OFFSET = 40;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct PassingData *s_ptrPassingData
     * }
     */
    public static final long s_ptrPassingData$offset() {
        return s_ptrPassingData$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct PassingData *s_ptrPassingData
     * }
     */
    public static MemorySegment s_ptrPassingData(MemorySegment struct) {
        return struct.get(s_ptrPassingData$LAYOUT, s_ptrPassingData$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct PassingData *s_ptrPassingData
     * }
     */
    public static void s_ptrPassingData(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(s_ptrPassingData$LAYOUT, s_ptrPassingData$OFFSET, fieldValue);
    }

    private static final AddressLayout s_string$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("s_string"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *s_string
     * }
     */
    public static final AddressLayout s_string$layout() {
        return s_string$LAYOUT;
    }

    private static final long s_string$OFFSET = 48;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *s_string
     * }
     */
    public static final long s_string$offset() {
        return s_string$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *s_string
     * }
     */
    public static MemorySegment s_string(MemorySegment struct) {
        return struct.get(s_string$LAYOUT, s_string$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *s_string
     * }
     */
    public static void s_string(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(s_string$LAYOUT, s_string$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

