// Generated by jextract

package jpassport.test.extracted;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class library_h {

    library_h() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();
    static final boolean TRACE_DOWNCALLS = Boolean.getBoolean("jextract.trace.downcalls");

    static void traceDowncall(String name, Object... args) {
         String traceArgs = Arrays.stream(args)
                       .map(Object::toString)
                       .collect(Collectors.joining(", "));
         System.out.printf("%s(%s)\n", name, traceArgs);
    }

    static MemorySegment findOrThrow(String symbol) {
        return SYMBOL_LOOKUP.find(symbol)
            .orElseThrow(() -> new UnsatisfiedLinkError("unresolved symbol: " + symbol));
    }

    static MethodHandle upcallHandle(Class<?> fi, String name, FunctionDescriptor fdesc) {
        try {
            return MethodHandles.lookup().findVirtual(fi, name, fdesc.toMethodType());
        } catch (ReflectiveOperationException ex) {
            throw new AssertionError(ex);
        }
    }

    static MemoryLayout align(MemoryLayout layout, long align) {
        return switch (layout) {
            case PaddingLayout p -> p;
            case ValueLayout v -> v.withByteAlignment(align);
            case GroupLayout g -> {
                MemoryLayout[] alignedMembers = g.memberLayouts().stream()
                        .map(m -> align(m, align)).toArray(MemoryLayout[]::new);
                yield g instanceof StructLayout ?
                        MemoryLayout.structLayout(alignedMembers) : MemoryLayout.unionLayout(alignedMembers);
            }
            case SequenceLayout s -> MemoryLayout.sequenceLayout(s.elementCount(), align(s.elementLayout(), align));
        };
    }

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.libraryLookup(System.mapLibraryName("libpassport_test"), LIBRARY_ARENA)
            .or(SymbolLookup.loaderLookup())
            .or(Linker.nativeLinker().defaultLookup());

    public static final ValueLayout.OfBoolean C_BOOL = ValueLayout.JAVA_BOOLEAN;
    public static final ValueLayout.OfByte C_CHAR = ValueLayout.JAVA_BYTE;
    public static final ValueLayout.OfShort C_SHORT = ValueLayout.JAVA_SHORT;
    public static final ValueLayout.OfInt C_INT = ValueLayout.JAVA_INT;
    public static final ValueLayout.OfLong C_LONG_LONG = ValueLayout.JAVA_LONG;
    public static final ValueLayout.OfFloat C_FLOAT = ValueLayout.JAVA_FLOAT;
    public static final ValueLayout.OfDouble C_DOUBLE = ValueLayout.JAVA_DOUBLE;
    public static final AddressLayout C_POINTER = ValueLayout.ADDRESS
            .withTargetLayout(MemoryLayout.sequenceLayout(java.lang.Long.MAX_VALUE, JAVA_BYTE));
    public static final ValueLayout.OfInt C_LONG = ValueLayout.JAVA_INT;
    public static final ValueLayout.OfDouble C_LONG_DOUBLE = ValueLayout.JAVA_DOUBLE;

    private static class sumD {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            library_h.C_DOUBLE,
            library_h.C_DOUBLE,
            library_h.C_DOUBLE
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("sumD");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern double sumD(double d1, double d2)
     * }
     */
    public static FunctionDescriptor sumD$descriptor() {
        return sumD.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern double sumD(double d1, double d2)
     * }
     */
    public static MethodHandle sumD$handle() {
        return sumD.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern double sumD(double d1, double d2)
     * }
     */
    public static MemorySegment sumD$address() {
        return sumD.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern double sumD(double d1, double d2)
     * }
     */
    public static double sumD(double d1, double d2) {
        var mh$ = sumD.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("sumD", d1, d2);
            }
            return (double)mh$.invokeExact(d1, d2);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class sumArrD {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            library_h.C_DOUBLE,
            library_h.C_POINTER,
            library_h.C_INT
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("sumArrD");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern double sumArrD(const double *arr, int count)
     * }
     */
    public static FunctionDescriptor sumArrD$descriptor() {
        return sumArrD.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern double sumArrD(const double *arr, int count)
     * }
     */
    public static MethodHandle sumArrD$handle() {
        return sumArrD.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern double sumArrD(const double *arr, int count)
     * }
     */
    public static MemorySegment sumArrD$address() {
        return sumArrD.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern double sumArrD(const double *arr, int count)
     * }
     */
    public static double sumArrD(MemorySegment arr, int count) {
        var mh$ = sumArrD.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("sumArrD", arr, count);
            }
            return (double)mh$.invokeExact(arr, count);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class sumArrDD {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            library_h.C_DOUBLE,
            library_h.C_POINTER,
            library_h.C_POINTER,
            library_h.C_INT
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("sumArrDD");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern double sumArrDD(const double *arr, const double *arr2, int count)
     * }
     */
    public static FunctionDescriptor sumArrDD$descriptor() {
        return sumArrDD.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern double sumArrDD(const double *arr, const double *arr2, int count)
     * }
     */
    public static MethodHandle sumArrDD$handle() {
        return sumArrDD.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern double sumArrDD(const double *arr, const double *arr2, int count)
     * }
     */
    public static MemorySegment sumArrDD$address() {
        return sumArrDD.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern double sumArrDD(const double *arr, const double *arr2, int count)
     * }
     */
    public static double sumArrDD(MemorySegment arr, MemorySegment arr2, int count) {
        var mh$ = sumArrDD.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("sumArrDD", arr, arr2, count);
            }
            return (double)mh$.invokeExact(arr, arr2, count);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class readD {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            library_h.C_POINTER,
            library_h.C_INT
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("readD");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern void readD(double *v, int set)
     * }
     */
    public static FunctionDescriptor readD$descriptor() {
        return readD.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern void readD(double *v, int set)
     * }
     */
    public static MethodHandle readD$handle() {
        return readD.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern void readD(double *v, int set)
     * }
     */
    public static MemorySegment readD$address() {
        return readD.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern void readD(double *v, int set)
     * }
     */
    public static void readD(MemorySegment v, int set) {
        var mh$ = readD.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("readD", v, set);
            }
            mh$.invokeExact(v, set);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class sumMatDPtrPtr {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            library_h.C_DOUBLE,
            library_h.C_INT,
            library_h.C_INT,
            library_h.C_POINTER
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("sumMatDPtrPtr");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern double sumMatDPtrPtr(int rows, int cols, const double **mat)
     * }
     */
    public static FunctionDescriptor sumMatDPtrPtr$descriptor() {
        return sumMatDPtrPtr.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern double sumMatDPtrPtr(int rows, int cols, const double **mat)
     * }
     */
    public static MethodHandle sumMatDPtrPtr$handle() {
        return sumMatDPtrPtr.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern double sumMatDPtrPtr(int rows, int cols, const double **mat)
     * }
     */
    public static MemorySegment sumMatDPtrPtr$address() {
        return sumMatDPtrPtr.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern double sumMatDPtrPtr(int rows, int cols, const double **mat)
     * }
     */
    public static double sumMatDPtrPtr(int rows, int cols, MemorySegment mat) {
        var mh$ = sumMatDPtrPtr.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("sumMatDPtrPtr", rows, cols, mat);
            }
            return (double)mh$.invokeExact(rows, cols, mat);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class sumArrF {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            library_h.C_FLOAT,
            library_h.C_POINTER,
            library_h.C_INT
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("sumArrF");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern float sumArrF(const float *arr, int count)
     * }
     */
    public static FunctionDescriptor sumArrF$descriptor() {
        return sumArrF.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern float sumArrF(const float *arr, int count)
     * }
     */
    public static MethodHandle sumArrF$handle() {
        return sumArrF.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern float sumArrF(const float *arr, int count)
     * }
     */
    public static MemorySegment sumArrF$address() {
        return sumArrF.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern float sumArrF(const float *arr, int count)
     * }
     */
    public static float sumArrF(MemorySegment arr, int count) {
        var mh$ = sumArrF.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("sumArrF", arr, count);
            }
            return (float)mh$.invokeExact(arr, count);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class readF {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            library_h.C_POINTER,
            library_h.C_FLOAT
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("readF");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern void readF(float *val, float set)
     * }
     */
    public static FunctionDescriptor readF$descriptor() {
        return readF.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern void readF(float *val, float set)
     * }
     */
    public static MethodHandle readF$handle() {
        return readF.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern void readF(float *val, float set)
     * }
     */
    public static MemorySegment readF$address() {
        return readF.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern void readF(float *val, float set)
     * }
     */
    public static void readF(MemorySegment val, float set) {
        var mh$ = readF.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("readF", val, set);
            }
            mh$.invokeExact(val, set);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class sumMatFPtrPtr {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            library_h.C_FLOAT,
            library_h.C_INT,
            library_h.C_INT,
            library_h.C_POINTER
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("sumMatFPtrPtr");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern float sumMatFPtrPtr(int rows, int cols, const float **mat)
     * }
     */
    public static FunctionDescriptor sumMatFPtrPtr$descriptor() {
        return sumMatFPtrPtr.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern float sumMatFPtrPtr(int rows, int cols, const float **mat)
     * }
     */
    public static MethodHandle sumMatFPtrPtr$handle() {
        return sumMatFPtrPtr.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern float sumMatFPtrPtr(int rows, int cols, const float **mat)
     * }
     */
    public static MemorySegment sumMatFPtrPtr$address() {
        return sumMatFPtrPtr.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern float sumMatFPtrPtr(int rows, int cols, const float **mat)
     * }
     */
    public static float sumMatFPtrPtr(int rows, int cols, MemorySegment mat) {
        var mh$ = sumMatFPtrPtr.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("sumMatFPtrPtr", rows, cols, mat);
            }
            return (float)mh$.invokeExact(rows, cols, mat);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class sumArrL {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            library_h.C_LONG_LONG,
            library_h.C_POINTER,
            library_h.C_LONG_LONG
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("sumArrL");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern long long sumArrL(const long long *arr, long long count)
     * }
     */
    public static FunctionDescriptor sumArrL$descriptor() {
        return sumArrL.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern long long sumArrL(const long long *arr, long long count)
     * }
     */
    public static MethodHandle sumArrL$handle() {
        return sumArrL.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern long long sumArrL(const long long *arr, long long count)
     * }
     */
    public static MemorySegment sumArrL$address() {
        return sumArrL.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern long long sumArrL(const long long *arr, long long count)
     * }
     */
    public static long sumArrL(MemorySegment arr, long count) {
        var mh$ = sumArrL.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("sumArrL", arr, count);
            }
            return (long)mh$.invokeExact(arr, count);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class readL {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            library_h.C_POINTER,
            library_h.C_LONG_LONG
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("readL");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern void readL(long long *val, long long set)
     * }
     */
    public static FunctionDescriptor readL$descriptor() {
        return readL.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern void readL(long long *val, long long set)
     * }
     */
    public static MethodHandle readL$handle() {
        return readL.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern void readL(long long *val, long long set)
     * }
     */
    public static MemorySegment readL$address() {
        return readL.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern void readL(long long *val, long long set)
     * }
     */
    public static void readL(MemorySegment val, long set) {
        var mh$ = readL.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("readL", val, set);
            }
            mh$.invokeExact(val, set);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class sumMatLPtrPtr {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            library_h.C_LONG_LONG,
            library_h.C_INT,
            library_h.C_INT,
            library_h.C_POINTER
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("sumMatLPtrPtr");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern long long sumMatLPtrPtr(int rows, int cols, const long long **mat)
     * }
     */
    public static FunctionDescriptor sumMatLPtrPtr$descriptor() {
        return sumMatLPtrPtr.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern long long sumMatLPtrPtr(int rows, int cols, const long long **mat)
     * }
     */
    public static MethodHandle sumMatLPtrPtr$handle() {
        return sumMatLPtrPtr.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern long long sumMatLPtrPtr(int rows, int cols, const long long **mat)
     * }
     */
    public static MemorySegment sumMatLPtrPtr$address() {
        return sumMatLPtrPtr.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern long long sumMatLPtrPtr(int rows, int cols, const long long **mat)
     * }
     */
    public static long sumMatLPtrPtr(int rows, int cols, MemorySegment mat) {
        var mh$ = sumMatLPtrPtr.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("sumMatLPtrPtr", rows, cols, mat);
            }
            return (long)mh$.invokeExact(rows, cols, mat);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class sumArrI {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            library_h.C_INT,
            library_h.C_POINTER,
            library_h.C_INT
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("sumArrI");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern int sumArrI(const int *arr, int count)
     * }
     */
    public static FunctionDescriptor sumArrI$descriptor() {
        return sumArrI.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern int sumArrI(const int *arr, int count)
     * }
     */
    public static MethodHandle sumArrI$handle() {
        return sumArrI.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern int sumArrI(const int *arr, int count)
     * }
     */
    public static MemorySegment sumArrI$address() {
        return sumArrI.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern int sumArrI(const int *arr, int count)
     * }
     */
    public static int sumArrI(MemorySegment arr, int count) {
        var mh$ = sumArrI.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("sumArrI", arr, count);
            }
            return (int)mh$.invokeExact(arr, count);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class readI {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            library_h.C_POINTER,
            library_h.C_INT
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("readI");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern void readI(int *val, int set)
     * }
     */
    public static FunctionDescriptor readI$descriptor() {
        return readI.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern void readI(int *val, int set)
     * }
     */
    public static MethodHandle readI$handle() {
        return readI.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern void readI(int *val, int set)
     * }
     */
    public static MemorySegment readI$address() {
        return readI.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern void readI(int *val, int set)
     * }
     */
    public static void readI(MemorySegment val, int set) {
        var mh$ = readI.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("readI", val, set);
            }
            mh$.invokeExact(val, set);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class sumMatIPtrPtr {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            library_h.C_INT,
            library_h.C_INT,
            library_h.C_INT,
            library_h.C_POINTER
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("sumMatIPtrPtr");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern int sumMatIPtrPtr(int rows, int cols, const int **mat)
     * }
     */
    public static FunctionDescriptor sumMatIPtrPtr$descriptor() {
        return sumMatIPtrPtr.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern int sumMatIPtrPtr(int rows, int cols, const int **mat)
     * }
     */
    public static MethodHandle sumMatIPtrPtr$handle() {
        return sumMatIPtrPtr.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern int sumMatIPtrPtr(int rows, int cols, const int **mat)
     * }
     */
    public static MemorySegment sumMatIPtrPtr$address() {
        return sumMatIPtrPtr.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern int sumMatIPtrPtr(int rows, int cols, const int **mat)
     * }
     */
    public static int sumMatIPtrPtr(int rows, int cols, MemorySegment mat) {
        var mh$ = sumMatIPtrPtr.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("sumMatIPtrPtr", rows, cols, mat);
            }
            return (int)mh$.invokeExact(rows, cols, mat);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class sumArrS {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            library_h.C_SHORT,
            library_h.C_POINTER,
            library_h.C_SHORT
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("sumArrS");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern short sumArrS(const short *arr, short count)
     * }
     */
    public static FunctionDescriptor sumArrS$descriptor() {
        return sumArrS.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern short sumArrS(const short *arr, short count)
     * }
     */
    public static MethodHandle sumArrS$handle() {
        return sumArrS.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern short sumArrS(const short *arr, short count)
     * }
     */
    public static MemorySegment sumArrS$address() {
        return sumArrS.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern short sumArrS(const short *arr, short count)
     * }
     */
    public static short sumArrS(MemorySegment arr, short count) {
        var mh$ = sumArrS.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("sumArrS", arr, count);
            }
            return (short)mh$.invokeExact(arr, count);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class readS {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            library_h.C_POINTER,
            library_h.C_SHORT
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("readS");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern void readS(short *val, short set)
     * }
     */
    public static FunctionDescriptor readS$descriptor() {
        return readS.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern void readS(short *val, short set)
     * }
     */
    public static MethodHandle readS$handle() {
        return readS.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern void readS(short *val, short set)
     * }
     */
    public static MemorySegment readS$address() {
        return readS.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern void readS(short *val, short set)
     * }
     */
    public static void readS(MemorySegment val, short set) {
        var mh$ = readS.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("readS", val, set);
            }
            mh$.invokeExact(val, set);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class sumMatSPtrPtr {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            library_h.C_INT,
            library_h.C_INT,
            library_h.C_INT,
            library_h.C_POINTER
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("sumMatSPtrPtr");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern int sumMatSPtrPtr(int rows, int cols, const short **mat)
     * }
     */
    public static FunctionDescriptor sumMatSPtrPtr$descriptor() {
        return sumMatSPtrPtr.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern int sumMatSPtrPtr(int rows, int cols, const short **mat)
     * }
     */
    public static MethodHandle sumMatSPtrPtr$handle() {
        return sumMatSPtrPtr.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern int sumMatSPtrPtr(int rows, int cols, const short **mat)
     * }
     */
    public static MemorySegment sumMatSPtrPtr$address() {
        return sumMatSPtrPtr.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern int sumMatSPtrPtr(int rows, int cols, const short **mat)
     * }
     */
    public static int sumMatSPtrPtr(int rows, int cols, MemorySegment mat) {
        var mh$ = sumMatSPtrPtr.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("sumMatSPtrPtr", rows, cols, mat);
            }
            return (int)mh$.invokeExact(rows, cols, mat);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class sumArrB {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            library_h.C_CHAR,
            library_h.C_POINTER,
            library_h.C_CHAR
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("sumArrB");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern char sumArrB(const char *arr, char count)
     * }
     */
    public static FunctionDescriptor sumArrB$descriptor() {
        return sumArrB.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern char sumArrB(const char *arr, char count)
     * }
     */
    public static MethodHandle sumArrB$handle() {
        return sumArrB.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern char sumArrB(const char *arr, char count)
     * }
     */
    public static MemorySegment sumArrB$address() {
        return sumArrB.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern char sumArrB(const char *arr, char count)
     * }
     */
    public static byte sumArrB(MemorySegment arr, byte count) {
        var mh$ = sumArrB.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("sumArrB", arr, count);
            }
            return (byte)mh$.invokeExact(arr, count);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class readB {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            library_h.C_POINTER,
            library_h.C_CHAR
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("readB");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern void readB(char *val, char set)
     * }
     */
    public static FunctionDescriptor readB$descriptor() {
        return readB.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern void readB(char *val, char set)
     * }
     */
    public static MethodHandle readB$handle() {
        return readB.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern void readB(char *val, char set)
     * }
     */
    public static MemorySegment readB$address() {
        return readB.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern void readB(char *val, char set)
     * }
     */
    public static void readB(MemorySegment val, byte set) {
        var mh$ = readB.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("readB", val, set);
            }
            mh$.invokeExact(val, set);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class sumMatBPtrPtr {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            library_h.C_INT,
            library_h.C_INT,
            library_h.C_INT,
            library_h.C_POINTER
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("sumMatBPtrPtr");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern int sumMatBPtrPtr(int rows, int cols, const char **mat)
     * }
     */
    public static FunctionDescriptor sumMatBPtrPtr$descriptor() {
        return sumMatBPtrPtr.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern int sumMatBPtrPtr(int rows, int cols, const char **mat)
     * }
     */
    public static MethodHandle sumMatBPtrPtr$handle() {
        return sumMatBPtrPtr.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern int sumMatBPtrPtr(int rows, int cols, const char **mat)
     * }
     */
    public static MemorySegment sumMatBPtrPtr$address() {
        return sumMatBPtrPtr.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern int sumMatBPtrPtr(int rows, int cols, const char **mat)
     * }
     */
    public static int sumMatBPtrPtr(int rows, int cols, MemorySegment mat) {
        var mh$ = sumMatBPtrPtr.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("sumMatBPtrPtr", rows, cols, mat);
            }
            return (int)mh$.invokeExact(rows, cols, mat);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cstringLength {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            library_h.C_INT,
            library_h.C_POINTER
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("cstringLength");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern int cstringLength(const char *string)
     * }
     */
    public static FunctionDescriptor cstringLength$descriptor() {
        return cstringLength.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern int cstringLength(const char *string)
     * }
     */
    public static MethodHandle cstringLength$handle() {
        return cstringLength.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern int cstringLength(const char *string)
     * }
     */
    public static MemorySegment cstringLength$address() {
        return cstringLength.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern int cstringLength(const char *string)
     * }
     */
    public static int cstringLength(MemorySegment string) {
        var mh$ = cstringLength.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cstringLength", string);
            }
            return (int)mh$.invokeExact(string);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class mallocString {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            library_h.C_POINTER,
            library_h.C_POINTER
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("mallocString");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern char *mallocString(const char *origString)
     * }
     */
    public static FunctionDescriptor mallocString$descriptor() {
        return mallocString.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern char *mallocString(const char *origString)
     * }
     */
    public static MethodHandle mallocString$handle() {
        return mallocString.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern char *mallocString(const char *origString)
     * }
     */
    public static MemorySegment mallocString$address() {
        return mallocString.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern char *mallocString(const char *origString)
     * }
     */
    public static MemorySegment mallocString(MemorySegment origString) {
        var mh$ = mallocString.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("mallocString", origString);
            }
            return (MemorySegment)mh$.invokeExact(origString);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class mallocDoubles {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            library_h.C_POINTER,
            library_h.C_INT
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("mallocDoubles");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern double *mallocDoubles(int count)
     * }
     */
    public static FunctionDescriptor mallocDoubles$descriptor() {
        return mallocDoubles.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern double *mallocDoubles(int count)
     * }
     */
    public static MethodHandle mallocDoubles$handle() {
        return mallocDoubles.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern double *mallocDoubles(int count)
     * }
     */
    public static MemorySegment mallocDoubles$address() {
        return mallocDoubles.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern double *mallocDoubles(int count)
     * }
     */
    public static MemorySegment mallocDoubles(int count) {
        var mh$ = mallocDoubles.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("mallocDoubles", count);
            }
            return (MemorySegment)mh$.invokeExact(count);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class freeMemory {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            library_h.C_POINTER
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("freeMemory");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern void freeMemory(byte []memory)
     * }
     */
    public static FunctionDescriptor freeMemory$descriptor() {
        return freeMemory.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern void freeMemory(byte []memory)
     * }
     */
    public static MethodHandle freeMemory$handle() {
        return freeMemory.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern void freeMemory(byte []memory)
     * }
     */
    public static MemorySegment freeMemory$address() {
        return freeMemory.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern void freeMemory(byte []memory)
     * }
     */
    public static void freeMemory(MemorySegment memory) {
        var mh$ = freeMemory.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("freeMemory", memory);
            }
            mh$.invokeExact(memory);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class readPointer {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            library_h.C_POINTER,
            library_h.C_LONG_LONG
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("readPointer");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern void readPointer(long long *val, long long set)
     * }
     */
    public static FunctionDescriptor readPointer$descriptor() {
        return readPointer.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern void readPointer(long long *val, long long set)
     * }
     */
    public static MethodHandle readPointer$handle() {
        return readPointer.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern void readPointer(long long *val, long long set)
     * }
     */
    public static MemorySegment readPointer$address() {
        return readPointer.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern void readPointer(long long *val, long long set)
     * }
     */
    public static void readPointer(MemorySegment val, long set) {
        var mh$ = readPointer.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("readPointer", val, set);
            }
            mh$.invokeExact(val, set);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class getPointer {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            library_h.C_LONG_LONG,
            library_h.C_POINTER,
            library_h.C_LONG_LONG
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("getPointer");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern long long getPointer(long long *val, long long set)
     * }
     */
    public static FunctionDescriptor getPointer$descriptor() {
        return getPointer.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern long long getPointer(long long *val, long long set)
     * }
     */
    public static MethodHandle getPointer$handle() {
        return getPointer.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern long long getPointer(long long *val, long long set)
     * }
     */
    public static MemorySegment getPointer$address() {
        return getPointer.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern long long getPointer(long long *val, long long set)
     * }
     */
    public static long getPointer(MemorySegment val, long set) {
        var mh$ = getPointer.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("getPointer", val, set);
            }
            return (long)mh$.invokeExact(val, set);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class fillChars {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            library_h.C_INT,
            library_h.C_POINTER,
            library_h.C_INT
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("fillChars");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern int fillChars(char *fillThis, int sizemax)
     * }
     */
    public static FunctionDescriptor fillChars$descriptor() {
        return fillChars.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern int fillChars(char *fillThis, int sizemax)
     * }
     */
    public static MethodHandle fillChars$handle() {
        return fillChars.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern int fillChars(char *fillThis, int sizemax)
     * }
     */
    public static MemorySegment fillChars$address() {
        return fillChars.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern int fillChars(char *fillThis, int sizemax)
     * }
     */
    public static int fillChars(MemorySegment fillThis, int sizemax) {
        var mh$ = fillChars.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("fillChars", fillThis, sizemax);
            }
            return (int)mh$.invokeExact(fillThis, sizemax);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class passChars {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            library_h.C_INT,
            library_h.C_POINTER,
            library_h.C_INT
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("passChars");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern int passChars(char *fillThis, int sizemax)
     * }
     */
    public static FunctionDescriptor passChars$descriptor() {
        return passChars.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern int passChars(char *fillThis, int sizemax)
     * }
     */
    public static MethodHandle passChars$handle() {
        return passChars.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern int passChars(char *fillThis, int sizemax)
     * }
     */
    public static MemorySegment passChars$address() {
        return passChars.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern int passChars(char *fillThis, int sizemax)
     * }
     */
    public static int passChars(MemorySegment fillThis, int sizemax) {
        var mh$ = passChars.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("passChars", fillThis, sizemax);
            }
            return (int)mh$.invokeExact(fillThis, sizemax);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class passStruct {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            library_h.C_DOUBLE,
            library_h.C_POINTER
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("passStruct");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern double passStruct(struct PassingData *data)
     * }
     */
    public static FunctionDescriptor passStruct$descriptor() {
        return passStruct.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern double passStruct(struct PassingData *data)
     * }
     */
    public static MethodHandle passStruct$handle() {
        return passStruct.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern double passStruct(struct PassingData *data)
     * }
     */
    public static MemorySegment passStruct$address() {
        return passStruct.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern double passStruct(struct PassingData *data)
     * }
     */
    public static double passStruct(MemorySegment data) {
        var mh$ = passStruct.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("passStruct", data);
            }
            return (double)mh$.invokeExact(data);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class passComplex {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            library_h.C_DOUBLE,
            library_h.C_POINTER
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("passComplex");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern double passComplex(struct ComplexPassing *complex)
     * }
     */
    public static FunctionDescriptor passComplex$descriptor() {
        return passComplex.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern double passComplex(struct ComplexPassing *complex)
     * }
     */
    public static MethodHandle passComplex$handle() {
        return passComplex.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern double passComplex(struct ComplexPassing *complex)
     * }
     */
    public static MemorySegment passComplex$address() {
        return passComplex.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern double passComplex(struct ComplexPassing *complex)
     * }
     */
    public static double passComplex(MemorySegment complex) {
        var mh$ = passComplex.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("passComplex", complex);
            }
            return (double)mh$.invokeExact(complex);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class passStructWithArrays {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            library_h.C_DOUBLE,
            library_h.C_POINTER
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("passStructWithArrays");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern double passStructWithArrays(struct PassingArrays *structWithArrays)
     * }
     */
    public static FunctionDescriptor passStructWithArrays$descriptor() {
        return passStructWithArrays.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern double passStructWithArrays(struct PassingArrays *structWithArrays)
     * }
     */
    public static MethodHandle passStructWithArrays$handle() {
        return passStructWithArrays.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern double passStructWithArrays(struct PassingArrays *structWithArrays)
     * }
     */
    public static MemorySegment passStructWithArrays$address() {
        return passStructWithArrays.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern double passStructWithArrays(struct PassingArrays *structWithArrays)
     * }
     */
    public static double passStructWithArrays(MemorySegment structWithArrays) {
        var mh$ = passStructWithArrays.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("passStructWithArrays", structWithArrays);
            }
            return (double)mh$.invokeExact(structWithArrays);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class passMemoryBlock {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            library_h.C_POINTER
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("passMemoryBlock");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern void passMemoryBlock(struct PassMemoryBlock *memoryBlock)
     * }
     */
    public static FunctionDescriptor passMemoryBlock$descriptor() {
        return passMemoryBlock.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern void passMemoryBlock(struct PassMemoryBlock *memoryBlock)
     * }
     */
    public static MethodHandle passMemoryBlock$handle() {
        return passMemoryBlock.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern void passMemoryBlock(struct PassMemoryBlock *memoryBlock)
     * }
     */
    public static MemorySegment passMemoryBlock$address() {
        return passMemoryBlock.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern void passMemoryBlock(struct PassMemoryBlock *memoryBlock)
     * }
     */
    public static void passMemoryBlock(MemorySegment memoryBlock) {
        var mh$ = passMemoryBlock.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("passMemoryBlock", memoryBlock);
            }
            mh$.invokeExact(memoryBlock);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class call_CB {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            library_h.C_INT,
            library_h.C_POINTER,
            library_h.C_INT,
            library_h.C_DOUBLE
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("call_CB");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern int call_CB(callbackFN fn, int, double)
     * }
     */
    public static FunctionDescriptor call_CB$descriptor() {
        return call_CB.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern int call_CB(callbackFN fn, int, double)
     * }
     */
    public static MethodHandle call_CB$handle() {
        return call_CB.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern int call_CB(callbackFN fn, int, double)
     * }
     */
    public static MemorySegment call_CB$address() {
        return call_CB.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern int call_CB(callbackFN fn, int, double)
     * }
     */
    public static int call_CB(MemorySegment fn, int x1, double x2) {
        var mh$ = call_CB.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("call_CB", fn, x1, x2);
            }
            return (int)mh$.invokeExact(fn, x1, x2);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class call_CBArr {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            library_h.C_POINTER,
            library_h.C_POINTER,
            library_h.C_INT
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("call_CBArr");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern void call_CBArr(callbackFNArr fn, int *, int)
     * }
     */
    public static FunctionDescriptor call_CBArr$descriptor() {
        return call_CBArr.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern void call_CBArr(callbackFNArr fn, int *, int)
     * }
     */
    public static MethodHandle call_CBArr$handle() {
        return call_CBArr.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern void call_CBArr(callbackFNArr fn, int *, int)
     * }
     */
    public static MemorySegment call_CBArr$address() {
        return call_CBArr.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern void call_CBArr(callbackFNArr fn, int *, int)
     * }
     */
    public static void call_CBArr(MemorySegment fn, MemorySegment x1, int x2) {
        var mh$ = call_CBArr.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("call_CBArr", fn, x1, x2);
            }
            mh$.invokeExact(fn, x1, x2);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class PassPointers {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            library_h.C_POINTER,
            library_h.C_POINTER
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("PassPointers");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * byte []PassPointers(byte []hMem)
     * }
     */
    public static FunctionDescriptor PassPointers$descriptor() {
        return PassPointers.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * byte []PassPointers(byte []hMem)
     * }
     */
    public static MethodHandle PassPointers$handle() {
        return PassPointers.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * byte []PassPointers(byte []hMem)
     * }
     */
    public static MemorySegment PassPointers$address() {
        return PassPointers.ADDR;
    }

    /**
     * {@snippet lang=c :
     * byte []PassPointers(byte []hMem)
     * }
     */
    public static MemorySegment PassPointers(MemorySegment hMem) {
        var mh$ = PassPointers.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("PassPointers", hMem);
            }
            return (MemorySegment)mh$.invokeExact(hMem);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class setAnError {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            library_h.C_INT
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("setAnError");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern void setAnError(int errval)
     * }
     */
    public static FunctionDescriptor setAnError$descriptor() {
        return setAnError.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern void setAnError(int errval)
     * }
     */
    public static MethodHandle setAnError$handle() {
        return setAnError.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern void setAnError(int errval)
     * }
     */
    public static MemorySegment setAnError$address() {
        return setAnError.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern void setAnError(int errval)
     * }
     */
    public static void setAnError(int errval) {
        var mh$ = setAnError.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("setAnError", errval);
            }
            mh$.invokeExact(errval);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class passStructArrBlock {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            library_h.C_DOUBLE,
            library_h.C_POINTER,
            library_h.C_INT,
            library_h.C_INT
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("passStructArrBlock");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern double passStructArrBlock(struct PassingData data[], int count, int multiply)
     * }
     */
    public static FunctionDescriptor passStructArrBlock$descriptor() {
        return passStructArrBlock.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern double passStructArrBlock(struct PassingData data[], int count, int multiply)
     * }
     */
    public static MethodHandle passStructArrBlock$handle() {
        return passStructArrBlock.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern double passStructArrBlock(struct PassingData data[], int count, int multiply)
     * }
     */
    public static MemorySegment passStructArrBlock$address() {
        return passStructArrBlock.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern double passStructArrBlock(struct PassingData data[], int count, int multiply)
     * }
     */
    public static double passStructArrBlock(MemorySegment data, int count, int multiply) {
        var mh$ = passStructArrBlock.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("passStructArrBlock", data, count, multiply);
            }
            return (double)mh$.invokeExact(data, count, multiply);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class passStructArrPtr {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            library_h.C_DOUBLE,
            library_h.C_POINTER,
            library_h.C_INT,
            library_h.C_INT
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("passStructArrPtr");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern double passStructArrPtr(struct PassingData **data, int count, int multiply)
     * }
     */
    public static FunctionDescriptor passStructArrPtr$descriptor() {
        return passStructArrPtr.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern double passStructArrPtr(struct PassingData **data, int count, int multiply)
     * }
     */
    public static MethodHandle passStructArrPtr$handle() {
        return passStructArrPtr.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern double passStructArrPtr(struct PassingData **data, int count, int multiply)
     * }
     */
    public static MemorySegment passStructArrPtr$address() {
        return passStructArrPtr.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern double passStructArrPtr(struct PassingData **data, int count, int multiply)
     * }
     */
    public static double passStructArrPtr(MemorySegment data, int count, int multiply) {
        var mh$ = passStructArrPtr.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("passStructArrPtr", data, count, multiply);
            }
            return (double)mh$.invokeExact(data, count, multiply);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class passStructOfStructs {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            library_h.C_DOUBLE,
            library_h.C_POINTER
        );

        public static final MemorySegment ADDR = library_h.findOrThrow("passStructOfStructs");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern double passStructOfStructs(struct PassingStructs *data)
     * }
     */
    public static FunctionDescriptor passStructOfStructs$descriptor() {
        return passStructOfStructs.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern double passStructOfStructs(struct PassingStructs *data)
     * }
     */
    public static MethodHandle passStructOfStructs$handle() {
        return passStructOfStructs.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern double passStructOfStructs(struct PassingStructs *data)
     * }
     */
    public static MemorySegment passStructOfStructs$address() {
        return passStructOfStructs.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern double passStructOfStructs(struct PassingStructs *data)
     * }
     */
    public static double passStructOfStructs(MemorySegment data) {
        var mh$ = passStructOfStructs.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("passStructOfStructs", data);
            }
            return (double)mh$.invokeExact(data);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
}

