// Generated by jextract

package jpassport.test.extracted;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct PassingArrays {
 *     double s_double[5];
 *     long long s_long[8];
 *     long long s_doublePtrCount;
 *     double *s_doublePtr;
 *     long long s_longPtrCount;
 *     long long *s_longPtr;
 * }
 * }
 */
public class PassingArrays {

    PassingArrays() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(5, library_h.C_DOUBLE).withName("s_double"),
        MemoryLayout.sequenceLayout(8, library_h.C_LONG_LONG).withName("s_long"),
        library_h.C_LONG_LONG.withName("s_doublePtrCount"),
        library_h.C_POINTER.withName("s_doublePtr"),
        library_h.C_LONG_LONG.withName("s_longPtrCount"),
        library_h.C_POINTER.withName("s_longPtr")
    ).withName("PassingArrays");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout s_double$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("s_double"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double s_double[5]
     * }
     */
    public static final SequenceLayout s_double$layout() {
        return s_double$LAYOUT;
    }

    private static final long s_double$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double s_double[5]
     * }
     */
    public static final long s_double$offset() {
        return s_double$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double s_double[5]
     * }
     */
    public static MemorySegment s_double(MemorySegment struct) {
        return struct.asSlice(s_double$OFFSET, s_double$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double s_double[5]
     * }
     */
    public static void s_double(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, s_double$OFFSET, s_double$LAYOUT.byteSize());
    }

    private static long[] s_double$DIMS = { 5 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * double s_double[5]
     * }
     */
    public static long[] s_double$dimensions() {
        return s_double$DIMS;
    }
    private static final VarHandle s_double$ELEM_HANDLE = s_double$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * double s_double[5]
     * }
     */
    public static double s_double(MemorySegment struct, long index0) {
        return (double)s_double$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * double s_double[5]
     * }
     */
    public static void s_double(MemorySegment struct, long index0, double fieldValue) {
        s_double$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final SequenceLayout s_long$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("s_long"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long long s_long[8]
     * }
     */
    public static final SequenceLayout s_long$layout() {
        return s_long$LAYOUT;
    }

    private static final long s_long$OFFSET = 40;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long long s_long[8]
     * }
     */
    public static final long s_long$offset() {
        return s_long$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long long s_long[8]
     * }
     */
    public static MemorySegment s_long(MemorySegment struct) {
        return struct.asSlice(s_long$OFFSET, s_long$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long long s_long[8]
     * }
     */
    public static void s_long(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, s_long$OFFSET, s_long$LAYOUT.byteSize());
    }

    private static long[] s_long$DIMS = { 8 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * long long s_long[8]
     * }
     */
    public static long[] s_long$dimensions() {
        return s_long$DIMS;
    }
    private static final VarHandle s_long$ELEM_HANDLE = s_long$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * long long s_long[8]
     * }
     */
    public static long s_long(MemorySegment struct, long index0) {
        return (long)s_long$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * long long s_long[8]
     * }
     */
    public static void s_long(MemorySegment struct, long index0, long fieldValue) {
        s_long$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final OfLong s_doublePtrCount$LAYOUT = (OfLong)$LAYOUT.select(groupElement("s_doublePtrCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long long s_doublePtrCount
     * }
     */
    public static final OfLong s_doublePtrCount$layout() {
        return s_doublePtrCount$LAYOUT;
    }

    private static final long s_doublePtrCount$OFFSET = 104;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long long s_doublePtrCount
     * }
     */
    public static final long s_doublePtrCount$offset() {
        return s_doublePtrCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long long s_doublePtrCount
     * }
     */
    public static long s_doublePtrCount(MemorySegment struct) {
        return struct.get(s_doublePtrCount$LAYOUT, s_doublePtrCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long long s_doublePtrCount
     * }
     */
    public static void s_doublePtrCount(MemorySegment struct, long fieldValue) {
        struct.set(s_doublePtrCount$LAYOUT, s_doublePtrCount$OFFSET, fieldValue);
    }

    private static final AddressLayout s_doublePtr$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("s_doublePtr"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double *s_doublePtr
     * }
     */
    public static final AddressLayout s_doublePtr$layout() {
        return s_doublePtr$LAYOUT;
    }

    private static final long s_doublePtr$OFFSET = 112;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double *s_doublePtr
     * }
     */
    public static final long s_doublePtr$offset() {
        return s_doublePtr$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double *s_doublePtr
     * }
     */
    public static MemorySegment s_doublePtr(MemorySegment struct) {
        return struct.get(s_doublePtr$LAYOUT, s_doublePtr$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double *s_doublePtr
     * }
     */
    public static void s_doublePtr(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(s_doublePtr$LAYOUT, s_doublePtr$OFFSET, fieldValue);
    }

    private static final OfLong s_longPtrCount$LAYOUT = (OfLong)$LAYOUT.select(groupElement("s_longPtrCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long long s_longPtrCount
     * }
     */
    public static final OfLong s_longPtrCount$layout() {
        return s_longPtrCount$LAYOUT;
    }

    private static final long s_longPtrCount$OFFSET = 120;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long long s_longPtrCount
     * }
     */
    public static final long s_longPtrCount$offset() {
        return s_longPtrCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long long s_longPtrCount
     * }
     */
    public static long s_longPtrCount(MemorySegment struct) {
        return struct.get(s_longPtrCount$LAYOUT, s_longPtrCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long long s_longPtrCount
     * }
     */
    public static void s_longPtrCount(MemorySegment struct, long fieldValue) {
        struct.set(s_longPtrCount$LAYOUT, s_longPtrCount$OFFSET, fieldValue);
    }

    private static final AddressLayout s_longPtr$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("s_longPtr"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long long *s_longPtr
     * }
     */
    public static final AddressLayout s_longPtr$layout() {
        return s_longPtr$LAYOUT;
    }

    private static final long s_longPtr$OFFSET = 128;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long long *s_longPtr
     * }
     */
    public static final long s_longPtr$offset() {
        return s_longPtr$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long long *s_longPtr
     * }
     */
    public static MemorySegment s_longPtr(MemorySegment struct) {
        return struct.get(s_longPtr$LAYOUT, s_longPtr$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long long *s_longPtr
     * }
     */
    public static void s_longPtr(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(s_longPtr$LAYOUT, s_longPtr$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

