// Generated by jextract

package jpassport.test.extracted;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct PassingData {
 *     int s_int;
 *     long long s_long;
 *     float s_float;
 *     double s_double;
 * }
 * }
 */
public class PassingData {

    PassingData() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        library_h.C_INT.withName("s_int"),
        MemoryLayout.paddingLayout(4),
        library_h.C_LONG_LONG.withName("s_long"),
        library_h.C_FLOAT.withName("s_float"),
        MemoryLayout.paddingLayout(4),
        library_h.C_DOUBLE.withName("s_double")
    ).withName("PassingData");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt s_int$LAYOUT = (OfInt)$LAYOUT.select(groupElement("s_int"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int s_int
     * }
     */
    public static final OfInt s_int$layout() {
        return s_int$LAYOUT;
    }

    private static final long s_int$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int s_int
     * }
     */
    public static final long s_int$offset() {
        return s_int$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int s_int
     * }
     */
    public static int s_int(MemorySegment struct) {
        return struct.get(s_int$LAYOUT, s_int$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int s_int
     * }
     */
    public static void s_int(MemorySegment struct, int fieldValue) {
        struct.set(s_int$LAYOUT, s_int$OFFSET, fieldValue);
    }

    private static final OfLong s_long$LAYOUT = (OfLong)$LAYOUT.select(groupElement("s_long"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long long s_long
     * }
     */
    public static final OfLong s_long$layout() {
        return s_long$LAYOUT;
    }

    private static final long s_long$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long long s_long
     * }
     */
    public static final long s_long$offset() {
        return s_long$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long long s_long
     * }
     */
    public static long s_long(MemorySegment struct) {
        return struct.get(s_long$LAYOUT, s_long$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long long s_long
     * }
     */
    public static void s_long(MemorySegment struct, long fieldValue) {
        struct.set(s_long$LAYOUT, s_long$OFFSET, fieldValue);
    }

    private static final OfFloat s_float$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("s_float"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float s_float
     * }
     */
    public static final OfFloat s_float$layout() {
        return s_float$LAYOUT;
    }

    private static final long s_float$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float s_float
     * }
     */
    public static final long s_float$offset() {
        return s_float$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float s_float
     * }
     */
    public static float s_float(MemorySegment struct) {
        return struct.get(s_float$LAYOUT, s_float$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float s_float
     * }
     */
    public static void s_float(MemorySegment struct, float fieldValue) {
        struct.set(s_float$LAYOUT, s_float$OFFSET, fieldValue);
    }

    private static final OfDouble s_double$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("s_double"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double s_double
     * }
     */
    public static final OfDouble s_double$layout() {
        return s_double$LAYOUT;
    }

    private static final long s_double$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double s_double
     * }
     */
    public static final long s_double$offset() {
        return s_double$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double s_double
     * }
     */
    public static double s_double(MemorySegment struct) {
        return struct.get(s_double$LAYOUT, s_double$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double s_double
     * }
     */
    public static void s_double(MemorySegment struct, double fieldValue) {
        struct.set(s_double$LAYOUT, s_double$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

