// Generated by jextract

package jpassport.test.extracted;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct PassingStructs {
 *     struct PassingData s_simple;
 *     struct PassingData array_data[3];
 *     int countofPtrs;
 *     struct PassingData **s_ptrtoptr;
 * }
 * }
 */
public class PassingStructs {

    PassingStructs() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        PassingData.layout().withName("s_simple"),
        MemoryLayout.sequenceLayout(3, PassingData.layout()).withName("array_data"),
        library_h.C_INT.withName("countofPtrs"),
        MemoryLayout.paddingLayout(4),
        library_h.C_POINTER.withName("s_ptrtoptr")
    ).withName("PassingStructs");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout s_simple$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("s_simple"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct PassingData s_simple
     * }
     */
    public static final GroupLayout s_simple$layout() {
        return s_simple$LAYOUT;
    }

    private static final long s_simple$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct PassingData s_simple
     * }
     */
    public static final long s_simple$offset() {
        return s_simple$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct PassingData s_simple
     * }
     */
    public static MemorySegment s_simple(MemorySegment struct) {
        return struct.asSlice(s_simple$OFFSET, s_simple$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct PassingData s_simple
     * }
     */
    public static void s_simple(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, s_simple$OFFSET, s_simple$LAYOUT.byteSize());
    }

    private static final SequenceLayout array_data$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("array_data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct PassingData array_data[3]
     * }
     */
    public static final SequenceLayout array_data$layout() {
        return array_data$LAYOUT;
    }

    private static final long array_data$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct PassingData array_data[3]
     * }
     */
    public static final long array_data$offset() {
        return array_data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct PassingData array_data[3]
     * }
     */
    public static MemorySegment array_data(MemorySegment struct) {
        return struct.asSlice(array_data$OFFSET, array_data$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct PassingData array_data[3]
     * }
     */
    public static void array_data(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, array_data$OFFSET, array_data$LAYOUT.byteSize());
    }

    private static long[] array_data$DIMS = { 3 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * struct PassingData array_data[3]
     * }
     */
    public static long[] array_data$dimensions() {
        return array_data$DIMS;
    }
    private static final MethodHandle array_data$ELEM_HANDLE = array_data$LAYOUT.sliceHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * struct PassingData array_data[3]
     * }
     */
    public static MemorySegment array_data(MemorySegment struct, long index0) {
        try {
            return (MemorySegment)array_data$ELEM_HANDLE.invokeExact(struct, 0L, index0);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * struct PassingData array_data[3]
     * }
     */
    public static void array_data(MemorySegment struct, long index0, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, array_data(struct, index0), 0L, PassingData.layout().byteSize());
    }

    private static final OfInt countofPtrs$LAYOUT = (OfInt)$LAYOUT.select(groupElement("countofPtrs"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int countofPtrs
     * }
     */
    public static final OfInt countofPtrs$layout() {
        return countofPtrs$LAYOUT;
    }

    private static final long countofPtrs$OFFSET = 128;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int countofPtrs
     * }
     */
    public static final long countofPtrs$offset() {
        return countofPtrs$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int countofPtrs
     * }
     */
    public static int countofPtrs(MemorySegment struct) {
        return struct.get(countofPtrs$LAYOUT, countofPtrs$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int countofPtrs
     * }
     */
    public static void countofPtrs(MemorySegment struct, int fieldValue) {
        struct.set(countofPtrs$LAYOUT, countofPtrs$OFFSET, fieldValue);
    }

    private static final AddressLayout s_ptrtoptr$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("s_ptrtoptr"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct PassingData **s_ptrtoptr
     * }
     */
    public static final AddressLayout s_ptrtoptr$layout() {
        return s_ptrtoptr$LAYOUT;
    }

    private static final long s_ptrtoptr$OFFSET = 136;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct PassingData **s_ptrtoptr
     * }
     */
    public static final long s_ptrtoptr$offset() {
        return s_ptrtoptr$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct PassingData **s_ptrtoptr
     * }
     */
    public static MemorySegment s_ptrtoptr(MemorySegment struct) {
        return struct.get(s_ptrtoptr$LAYOUT, s_ptrtoptr$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct PassingData **s_ptrtoptr
     * }
     */
    public static void s_ptrtoptr(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(s_ptrtoptr$LAYOUT, s_ptrtoptr$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

